services:
  node-exporter:
    pid: host
    network_mode: host
    volumes:
      - '/:/host:rw,rslave'
    image: 'prom/node-exporter'

  prometheus:
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - '/etc/prometheus/:/etc/prometheus'
    image: 'prom/prometheus'
    entrypoint: ["sleep", "infinity"]

  grafana:
    container_name: grafana
    ports:
      - '3000:3000'
    image: 'grafana/grafana'

